using System.Linq;
using System.Numerics;
using System.Threading;
using Content.Client.Message;
using Content.Client.Examine;
using Content.Client.Hands.Systems;
using Content.Client.Store.Ui;
using Content.Shared.FixedPoint;
using Content.Shared.Imperial.Medieval.ArmorIntegrity;
using Content.Shared.Imperial.Medieval.Chemistry;
using Content.Shared.Imperial.Medieval.Trading;
using Content.Shared.Imperial.Medieval.Trading.Prototypes;
using Content.Shared.Input;
using Content.Shared.Item;
using Content.Shared.MedievalMeleeResource.Components;
using Content.Shared.Stacks;
using Content.Shared.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Timer = Robust.Shared.Timing.Timer;

namespace Content.Client.Imperial.Medieval.Trading;

[GenerateTypedNameReferences]
public sealed partial class TradingMenu : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototypes = default!;
    [Dependency] private readonly IEntityManager _entities = default!;

    public event Action<Guid>? OnBuy;
    public event Action<Guid>? OnSell;
    public event Action<int>? OnCreateSellOffer;
    public event Action<Guid, int>? OnCreateBuyOffer;
    public event Action<int>? OnCreateBuyOfferFromHeld;
    public event Action<Guid>? OnCancelOffer;
    public event Action<NetEntity>? OnCollectStoredItem;
    public event Action<int>? OnWithdraw;

    private readonly CancellationTokenSource _previewRetryCancellation = new();
    private TradingUpdateState? _state;
    private TradingMarketSection _section = TradingMarketSection.Common;
    private ProtoId<GuildTypePrototype>? _category;
    private Guid? _selected;
    private CurrencyPrototype? _currency;
    private StoreWithdrawWindow? _withdrawWindow;
    private int _previewRetry;
    private bool _management;

    public TradingMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CommonButton.OnPressed += _ => SelectSection(TradingMarketSection.Common);
        UniqueButton.OnPressed += _ => SelectSection(TradingMarketSection.Unique);
        ManagementButton.OnPressed += _ => SelectManagement();
        SearchBar.OnTextChanged += _ => RebuildItems();
        WithdrawButton.OnPressed += _ => OpenWithdrawWindow();
        CreateBuyOrderButton.OnPressed += _ => CreateSelectedBuyOrder();
        CreateSellOfferButton.OnPressed += _ => SubmitPrice(HeldPrice.Text, OnCreateSellOffer);
        CreateHeldBuyOrderButton.OnPressed += _ => SubmitPrice(HeldPrice.Text, OnCreateBuyOfferFromHeld);
        OnResized += UpdateColumns;
    }

    public void UpdateState(TradingUpdateState state)
    {
        _state = state;
        UpdateBalance();
        RebuildCategories();

        if (_selected == null || state.Items.All(item => item.CommodityId != _selected.Value))
            _selected = state.Items.FirstOrDefault(item => HasSection(item, _section))?.CommodityId;

        RebuildItems();
        RebuildSelected();
        RebuildManagement();
        UpdateSectionVisibility();
        _previewRetry = 0;
        RetryMissingPreviews(state);
    }

    private void SelectSection(TradingMarketSection section)
    {
        _management = false;
        _section = section;
        _category = null;
        _selected = _state?.Items.FirstOrDefault(item => HasSection(item, section))?.CommodityId;
        RebuildCategories();
        RebuildItems();
        RebuildSelected();
        UpdateSectionVisibility();
    }

    private void SelectManagement()
    {
        _management = true;
        RebuildManagement();
        UpdateSectionVisibility();
    }

    private void UpdateSectionVisibility()
    {
        MarketView.Visible = !_management;
        ManagementView.Visible = _management;
        SearchBar.Visible = !_management;
        OfferCreationPanel.Visible = !_management;
    }

    private void UpdateBalance()
    {
        if (_state == null)
            return;

        var text = _state.Balance.ToString();
        if (_prototypes.TryIndex(_state.Currency, out _currency))
            text = $"{Loc.GetString(_currency.DisplayName, ("amount", _state.Balance))}: {_state.Balance}";

        BalanceInfo.SetMarkup(text);
        WithdrawButton.Disabled = _state.Balance <= 0 || _currency?.CanWithdraw != true;
    }

    private void RebuildCategories()
    {
        CategoryContainer.DisposeAllChildren();
        CategoryContainer.Visible = !_management && _section == TradingMarketSection.Common;
        if (_management || _section != TradingMarketSection.Common || _state == null)
            return;

        var all = new Button { Text = "Все категории", HorizontalExpand = true };
        all.OnPressed += _ =>
        {
            _category = null;
            RebuildItems();
        };
        CategoryContainer.AddChild(all);

        var categories = _state.Items
            .Where(item => HasSection(item, TradingMarketSection.Common))
            .SelectMany(item => item.Categories)
            .Distinct()
            .OrderBy(GetCategoryName);
        foreach (var category in categories)
        {
            var captured = category;
            var button = new Button
            {
                Text = GetCategoryName(category),
                HorizontalExpand = true,
            };
            button.OnPressed += _ =>
            {
                _category = captured;
                RebuildItems();
            };
            CategoryContainer.AddChild(button);
        }
    }

    private string GetCategoryName(ProtoId<GuildTypePrototype> category)
    {
        return Loc.GetString($"trading-guild-type-{category.Id}");
    }

    private void RebuildItems()
    {
        ItemsGrid.DisposeAllChildren();
        if (_management || _state == null)
            return;

        var search = SearchBar.Text.Trim();
        var filtered = _state.Items
            .Where(item => string.IsNullOrEmpty(search)
                ? HasSection(item, _section) &&
                  (_section == TradingMarketSection.Unique || _category == null || item.Categories.Contains(_category.Value))
                : item.DisplayName.Contains(search, StringComparison.CurrentCultureIgnoreCase))
            .OrderBy(item => item.DisplayName);

        foreach (var item in filtered)
        {
            ItemsGrid.AddChild(CreateCard(item));
        }

        UpdateColumns();
    }

    private Control CreateCard(TradingMarketItemState item)
    {
        var panel = new PanelContainer
        {
            SetSize = new Vector2(180, 180),
            MinSize = new Vector2(180, 180),
            Margin = new Thickness(3),
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#171512"),
                BorderColor = _selected == item.CommodityId ? Color.FromHex("#d1a64b") : Color.FromHex("#4e4638"),
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 5,
                ContentMarginRightOverride = 5,
                ContentMarginTopOverride = 5,
                ContentMarginBottomOverride = 5,
            },
        };
        var content = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalExpand = true,
        };
        var select = new Button
        {
            HorizontalExpand = true,
            VerticalExpand = true,
        };
        var identity = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalExpand = true,
        };
        identity.AddChild(CreateItemPreview(item, new Vector2(82, 82)));
        identity.AddChild(new Label
        {
            Text = item.DisplayName,
            HorizontalAlignment = HAlignment.Center,
            ClipText = true,
        });
        select.AddChild(identity);
        select.OnPressed += _ =>
        {
            _selected = item.CommodityId;
            RebuildItems();
            RebuildSelected();
        };
        content.AddChild(select);

        var actions = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(0, 4, 0, 0),
        };
        var buy = new Button
        {
            Text = item.LowestSellPrice?.ToString() ?? "—",
            Disabled = item.LowestSellPrice == null || item.LowestSellPrice > _state!.Balance,
            HorizontalExpand = true,
            StyleBoxOverride = CreateActionButtonStyle("#b8860b", "#e3c565"),
        };
        buy.Label.FontColorOverride = Color.White;
        buy.OnPressed += _ => OnBuy?.Invoke(item.CommodityId);
        var sell = new Button
        {
            Text = item.HighestBuyPrice?.ToString() ?? "—",
            Disabled = item.HighestBuyPrice == null,
            HorizontalExpand = true,
            Margin = new Thickness(4, 0, 0, 0),
            StyleBoxOverride = CreateActionButtonStyle("#9c2f2f", "#d8675d"),
        };
        sell.Label.FontColorOverride = Color.White;
        sell.OnPressed += _ => OnSell?.Invoke(item.CommodityId);
        actions.AddChild(buy);
        actions.AddChild(sell);
        content.AddChild(actions);
        panel.AddChild(content);
        return panel;
    }

    private static StyleBoxFlat CreateActionButtonStyle(string background, string border)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex(background),
            BorderColor = Color.FromHex(border),
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 6,
            ContentMarginRightOverride = 6,
            ContentMarginTopOverride = 3,
            ContentMarginBottomOverride = 3,
        };
    }

    private void RebuildSelected()
    {
        OffersContainer.DisposeAllChildren();
        if (_management || _state == null || _selected == null)
        {
            SelectedName.Text = "Выберите товар";
            SelectedPreview.DisposeAllChildren();
            SelectedStats.SetMarkup(string.Empty);
            CreateBuyOrderButton.Disabled = true;
            return;
        }

        var item = _state.Items.FirstOrDefault(value => value.CommodityId == _selected.Value);
        if (item == null)
            return;

        SelectedName.Text = item.DisplayName;
        SelectedPreview.DisposeAllChildren();
        SelectedPreview.AddChild(CreateItemPreview(item, new Vector2(96, 96)));
        SelectedStats.SetMarkup(
            $"Спрос: {item.Demand:0.0}\nПредложение: {item.Supply:0.0}\nЛоты: {item.SellOfferCount} · Заказы: {item.BuyOfferCount}");
        CreateBuyOrderButton.Disabled = false;

        var offers = _state.Offers
            .Where(offer => offer.CommodityId == item.CommodityId)
            .OrderBy(offer => offer.Side)
            .ThenBy(offer => offer.Side == TradingOfferSide.Sell ? offer.Price : -offer.Price);
        foreach (var offer in offers)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 3),
            };
            row.AddChild(new Label
            {
                Text = offer.Side == TradingOfferSide.Sell ? "Лот" : "Заказ",
                MinWidth = 54,
            });
            row.AddChild(new Label
            {
                Text = $"{offer.ParticipantName}: {offer.Price}",
                HorizontalExpand = true,
                ClipText = true,
            });
            if (offer.IsOwn)
            {
                var cancel = new Button { Text = "×", MinWidth = 28 };
                cancel.OnPressed += _ => OnCancelOffer?.Invoke(offer.Id);
                row.AddChild(cancel);
            }
            OffersContainer.AddChild(row);
        }
    }

    private void CreateSelectedBuyOrder()
    {
        if (_selected == null || !TryParsePrice(BuyPrice.Text, out var price))
            return;
        OnCreateBuyOffer?.Invoke(_selected.Value, price);
    }

    private void RebuildManagement()
    {
        ManagedOffersContainer.DisposeAllChildren();
        StoredItemsContainer.DisposeAllChildren();
        if (_state == null)
            return;

        var ownOffers = _state.Offers.Where(offer => offer.IsOwn).ToList();
        if (ownOffers.Count == 0)
            ManagedOffersContainer.AddChild(new Label { Text = "Нет активных лотов и заказов" });

        foreach (var offer in ownOffers)
        {
            var row = CreateManagementRow(
                offer.ProductEntity,
                offer.PreviewEntity,
                offer.DisplayName,
                offer.Side == TradingOfferSide.Sell
                    ? $"Лот · {offer.Price}"
                    : $"Заказ · {offer.Price}");
            var cancel = new Button
            {
                Text = offer.Side == TradingOfferSide.Sell ? "Отменить и забрать" : "Отменить",
                MinWidth = 150,
            };
            cancel.OnPressed += _ => OnCancelOffer?.Invoke(offer.Id);
            row.AddChild(cancel);
            ManagedOffersContainer.AddChild(row);
        }

        if (_state.StoredItems.Count == 0)
            StoredItemsContainer.AddChild(new Label { Text = "Нет предметов для получения" });

        foreach (var stored in _state.StoredItems)
        {
            var row = CreateManagementRow(
                stored.ProductEntity,
                stored.Item,
                stored.DisplayName,
                "Получен по заказу");
            var collect = new Button { Text = "Получить", MinWidth = 150 };
            collect.OnPressed += _ => OnCollectStoredItem?.Invoke(stored.Item);
            row.AddChild(collect);
            StoredItemsContainer.AddChild(row);
        }
    }

    private BoxContainer CreateManagementRow(
        EntProtoId product,
        NetEntity? preview,
        string displayName,
        string status)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(4),
        };
        row.AddChild(CreateItemPreview(product, preview, new Vector2(54, 54)));
        var labels = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(8, 0),
        };
        labels.AddChild(new Label { Text = displayName, ClipText = true });
        labels.AddChild(new Label { Text = status, StyleClasses = { "LabelSubText" } });
        row.AddChild(labels);
        return row;
    }

    private static void SubmitPrice(string text, Action<int>? action)
    {
        if (TryParsePrice(text, out var price))
            action?.Invoke(price);
    }

    private static bool TryParsePrice(string text, out int price)
    {
        return int.TryParse(text, out price) && price > 0;
    }

    private Control CreateItemPreview(TradingMarketItemState item, Vector2 size)
    {
        return CreateItemPreview(item.ProductEntity, item.PreviewEntity, size);
    }

    private Control CreateItemPreview(EntProtoId product, NetEntity? preview, Vector2 size)
    {
        SpriteView view;
        if (ResolvePreview(preview) is { } entity)
        {
            view = new SpriteView
            {
                MinSize = size,
                SetSize = size,
                Stretch = SpriteView.StretchMode.Fill,
            };
            view.SetEntity(entity);
        }
        else if (_prototypes.HasIndex(product))
        {
            var prototypeView = new EntityPrototypeView
            {
                MinSize = size,
                SetSize = size,
                Stretch = SpriteView.StretchMode.Fill,
            };
            prototypeView.SetPrototype(product);
            view = prototypeView;
        }
        else
        {
            return new Control
            {
                MinSize = size,
                SetSize = size,
            };
        }

        view.MouseFilter = Control.MouseFilterMode.Pass;
        view.OnKeyBindDown += args =>
        {
            if (args.Function != ContentKeyFunctions.ExamineEntity ||
                view.Entity is not { } viewed ||
                !_entities.EntityExists(viewed.Owner))
            {
                return;
            }

            _entities.System<ExamineSystem>().DoExamine(viewed.Owner);
            args.Handle();
        };
        return view;
    }

    private EntityUid? ResolvePreview(TradingMarketItemState item)
    {
        return ResolvePreview(item.PreviewEntity);
    }

    private EntityUid? ResolvePreview(NetEntity? preview)
    {
        if (preview is not { } netEntity)
            return null;

        var entity = _entities.GetEntity(netEntity);
        return entity.Valid && _entities.EntityExists(entity) ? entity : null;
    }

    private static bool HasSection(TradingMarketItemState item, TradingMarketSection section)
    {
        return (item.Sections & section) != 0;
    }

    private void RetryMissingPreviews(TradingUpdateState state)
    {
        if (_previewRetry >= 20 || !HasMissingPreviews(state))
            return;

        Timer.Spawn(100, () =>
        {
            if (_state != state || !IsOpen || Disposed)
                return;

            _previewRetry++;
            RebuildItems();
            RebuildSelected();
            RebuildManagement();
            RetryMissingPreviews(state);
        }, _previewRetryCancellation.Token);
    }

    private bool HasMissingPreviews(TradingUpdateState state)
    {
        return state.Items.Any(item => item.PreviewEntity != null && ResolvePreview(item) == null) ||
               state.Offers.Any(offer => offer.IsOwn &&
                                         offer.PreviewEntity != null &&
                                         ResolvePreview(offer.PreviewEntity) == null) ||
               state.StoredItems.Any(item => ResolvePreview(item.Item) == null);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateHeldCategory();
    }

    private void UpdateHeldCategory()
    {
        var category = GetHeldCategory();
        var text = $"Появится: {category}";
        if (HeldCategory.Text != text)
            HeldCategory.Text = text;
    }

    private string GetHeldCategory()
    {
        if (_state == null ||
            _entities.System<HandsSystem>().GetActiveHandEntity() is not { } held ||
            !_entities.EntityExists(held) ||
            !_entities.TryGetComponent<MetaDataComponent>(held, out var metadata) ||
            metadata.EntityPrototype?.ID is not { } product ||
            !_entities.HasComponent<ItemComponent>(held))
        {
            return "—";
        }

        if (_prototypes.TryIndex(product, out var prototype) &&
            prototype.TryGetComponent<MedievalCurrencyComponent>(out _, _entities.ComponentFactory))
            return "нельзя выставить";

        var common = _state.Items.FirstOrDefault(item =>
            item.IsCommonBaseline && item.ProductEntity.Id == product);
        var isRecipe = _entities.HasComponent<MedievalRandomChemistryRecipeComponent>(held);
        var isEquipment = false;
        var pristine = true;

        if (_entities.TryGetComponent<MedievalMeleeResourceComponent>(held, out var weapon))
        {
            isEquipment = true;
            pristine &= weapon.Resource > 80f;
        }

        if (_entities.TryGetComponent<MedievalArmorIntegrityComponent>(held, out var armor))
        {
            isEquipment = true;
            pristine &= MathHelper.CloseTo(armor.MaxArmorHP, armor.ContainerArmorHP) &&
                        MathHelper.CloseTo(armor.CurrentArmorHP, armor.ContainerArmorHP);
        }

        if (isRecipe)
            return "уникальный";

        if (isEquipment)
            return common != null && pristine ? "общий/уникальный" : "уникальный";

        if (common == null)
            return "уникальный";

        var hasStack = _entities.TryGetComponent<StackComponent>(held, out var stack);
        var stackCount = stack?.Count ?? 1;
        return common.HasStack == hasStack && common.BaselineStackCount == stackCount
            ? "общий"
            : "уникальный";
    }

    private void OpenWithdrawWindow()
    {
        if (_state == null || _currency == null)
            return;

        if (_withdrawWindow is { IsOpen: true })
        {
            _withdrawWindow.MoveToFront();
            return;
        }

        _withdrawWindow = new StoreWithdrawWindow();
        _withdrawWindow.OpenCentered();
        _withdrawWindow.CreateCurrencyButtons(new Dictionary<ProtoId<CurrencyPrototype>, FixedPoint2>
        {
            { _currency, _state.Balance },
        });
        _withdrawWindow.OnWithdrawAttempt += (_, _, amount) => OnWithdraw?.Invoke(amount);
    }

    private void UpdateColumns()
    {
        ItemsGrid.Columns = Math.Max(1, (int) (ItemsGrid.Width / 190));
    }

    public override void Close()
    {
        _previewRetryCancellation.Cancel();
        base.Close();
        _withdrawWindow?.Close();
    }
}
