using System.Linq;
using System.Numerics;
using Content.Client.Message;
using Content.Client.Examine;
using Content.Client.Hands.Systems;
using Content.Client.Store.Ui;
using Content.Shared.FixedPoint;
using Content.Shared.Imperial.Medieval.Trading;
using Content.Shared.Imperial.Medieval.Trading.Prototypes;
using Content.Shared.Input;
using Content.Shared.Item;
using Content.Shared.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.Imperial.Medieval.Trading;

[GenerateTypedNameReferences]
public sealed partial class TradingMenu : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototypes = default!;
    [Dependency] private readonly IEntityManager _entities = default!;

    public event Action<Guid>? OnBuy;
    public event Action<Guid>? OnSell;
    public event Action<Guid>? OnBuyOffer;
    public event Action<Guid>? OnSellOffer;
    public event Action<Guid>? OnSelectCommodity;
    public event Action<int>? OnCreateSellOffer;
    public event Action<Guid, int>? OnCreateBuyOffer;
    public event Action<int>? OnCreateBuyOfferFromHeld;
    public event Action<Guid>? OnCancelOffer;
    public event Action<NetEntity>? OnCollectStoredItem;
    public event Action<int>? OnWithdraw;

    private TradingUpdateState? _state;
    private TradingMarketSection _section = TradingMarketSection.Common;
    private ProtoId<GuildTypePrototype>? _category;
    private Guid? _selected;
    private CurrencyPrototype? _currency;
    private StoreWithdrawWindow? _withdrawWindow;
    private bool _management;
    private bool _archive;
    private readonly Dictionary<EntProtoId, EntityUid> _prototypeExamineEntities = new();

    public TradingMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CommonButton.OnPressed += _ => SelectSection(TradingMarketSection.Common);
        UniqueButton.OnPressed += _ => SelectSection(TradingMarketSection.Unique);
        ManagementButton.OnPressed += _ => SelectManagement();
        ArchiveButton.OnPressed += _ => SelectArchive();
        SearchBar.OnTextChanged += _ => RebuildItems();
        WithdrawButton.OnPressed += _ => OpenWithdrawWindow();
        CreateBuyOrderButton.OnPressed += _ => CreateSelectedBuyOrder();
        CreateSellOfferButton.OnPressed += _ => SubmitPrice(HeldPrice.Text, OnCreateSellOffer);
        CreateHeldBuyOrderButton.OnPressed += _ => SubmitPrice(HeldPrice.Text, OnCreateBuyOfferFromHeld);
        OnResized += UpdateColumns;
    }

    public void UpdateState(TradingUpdateState state)
    {
        _state = state;
        UpdateBalance();
        RebuildCategories();

        var previousSelection = _selected;
        if (_selected == null || state.Items.All(item => item.CommodityId != _selected.Value))
            _selected = state.Items.FirstOrDefault(item => HasSection(item, _section))?.CommodityId;

        if (_selected != previousSelection && _selected is { } selected)
            OnSelectCommodity?.Invoke(selected);

        RebuildItems();
        RebuildSelected();
        RebuildManagement();
        RebuildArchive();
        UpdateSectionVisibility();
    }

    private void SelectSection(TradingMarketSection section)
    {
        _management = false;
        _archive = false;
        _section = section;
        _category = null;
        _selected = _state?.Items.FirstOrDefault(item => HasSection(item, section))?.CommodityId;
        if (_selected is { } selected)
            OnSelectCommodity?.Invoke(selected);
        RebuildCategories();
        RebuildItems();
        RebuildSelected();
        UpdateSectionVisibility();
    }

    private void SelectManagement()
    {
        _management = true;
        _archive = false;
        RebuildManagement();
        UpdateSectionVisibility();
    }

    private void SelectArchive()
    {
        _management = false;
        _archive = true;
        RebuildArchive();
        UpdateSectionVisibility();
    }

    private void UpdateSectionVisibility()
    {
        var marketVisible = !_management && !_archive;
        MarketView.Visible = marketVisible;
        ManagementView.Visible = _management;
        ArchiveView.Visible = _archive;
        SearchBar.Visible = marketVisible;
        OfferCreationPanel.Visible = marketVisible;
        CategoryPanel.Visible = marketVisible && _section == TradingMarketSection.Common;
    }

    private void UpdateBalance()
    {
        if (_state == null)
            return;

        var text = _state.Balance.ToString();
        if (_prototypes.TryIndex(_state.Currency, out _currency))
            text = $"{Loc.GetString(_currency.DisplayName, ("amount", _state.Balance))}: {_state.Balance}";

        BalanceInfo.SetMarkup(text);
        WithdrawButton.Disabled = _state.Balance <= 0 || _currency?.CanWithdraw != true;
    }

    private void RebuildCategories()
    {
        CategoryContainer.DisposeAllChildren();
        CategoryContainer.Visible = !_management && !_archive && _section == TradingMarketSection.Common;
        if (_management || _archive || _section != TradingMarketSection.Common || _state == null)
            return;

        var all = new Button { Text = "Все категории", HorizontalExpand = true };
        all.OnPressed += _ =>
        {
            _category = null;
            RebuildItems();
        };
        CategoryContainer.AddChild(all);

        var categories = _state.Items
            .Where(item => HasSection(item, TradingMarketSection.Common))
            .SelectMany(item => item.Categories)
            .Distinct()
            .OrderBy(GetCategoryName);
        foreach (var category in categories)
        {
            var captured = category;
            var button = new Button
            {
                Text = GetCategoryName(category),
                HorizontalExpand = true,
            };
            button.OnPressed += _ =>
            {
                _category = captured;
                RebuildItems();
            };
            CategoryContainer.AddChild(button);
        }
    }

    private string GetCategoryName(ProtoId<GuildTypePrototype> category)
    {
        return Loc.GetString($"trading-guild-type-{category.Id}");
    }

    private void RebuildItems()
    {
        ItemsGrid.DisposeAllChildren();
        if (_management || _archive || _state == null)
            return;

        var search = SearchBar.Text.Trim();
        var filtered = _state.Items
            .Where(item => string.IsNullOrEmpty(search)
                ? HasSection(item, _section) &&
                  (_section == TradingMarketSection.Unique || _category == null || item.Categories.Contains(_category.Value))
                : item.DisplayName.Contains(search, StringComparison.CurrentCultureIgnoreCase))
            .OrderBy(item => item.DisplayName);

        foreach (var item in filtered)
        {
            ItemsGrid.AddChild(CreateCard(item));
        }

        UpdateColumns();
    }

    private Control CreateCard(TradingMarketItemState item)
    {
        var panel = new PanelContainer
        {
            SetSize = new Vector2(176, 200),
            MinSize = new Vector2(176, 200),
            Margin = new Thickness(3),
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#171512"),
                BorderColor = _selected == item.CommodityId ? Color.FromHex("#d1a64b") : Color.FromHex("#4e4638"),
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 5,
                ContentMarginRightOverride = 5,
                ContentMarginTopOverride = 5,
                ContentMarginBottomOverride = 5,
            },
        };
        var content = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalExpand = true,
        };
        var select = new Button
        {
            HorizontalExpand = true,
            MinHeight = 112,
            SetHeight = 112,
        };
        select.AddChild(CreateItemPreview(item, new Vector2(88, 88)));
        select.OnPressed += _ =>
        {
            _selected = item.CommodityId;
            OnSelectCommodity?.Invoke(item.CommodityId);
            RebuildItems();
            RebuildSelected();
        };
        content.AddChild(select);
        var namePanel = new PanelContainer
        {
            MinHeight = 36,
            SetHeight = 36,
            HorizontalExpand = true,
            Margin = new Thickness(0, 3, 0, 0),
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#29251f"),
                BorderColor = Color.FromHex("#554b3d"),
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 4,
                ContentMarginRightOverride = 4,
                ContentMarginTopOverride = 2,
                ContentMarginBottomOverride = 2,
            },
        };
        namePanel.AddChild(new Label
        {
            Text = item.DisplayName,
            ToolTip = item.DisplayName,
            MinSize = new Vector2(154, 30),
            SetSize = new Vector2(154, 30),
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
            Align = Label.AlignMode.Center,
            VAlign = Label.VAlignMode.Center,
            ClipText = true,
            FontColorOverride = item.IsDamagedEquipment ? Color.FromHex("#e65353") : Color.White,
        });
        content.AddChild(namePanel);

        var actions = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            MinHeight = 30,
            SetHeight = 30,
            Margin = new Thickness(0, 4, 0, 0),
        };
        var buy = new Button
        {
            Text = item.LowestSellPrice?.ToString() ?? "—",
            Disabled = item.LowestSellPrice == null || item.LowestSellPrice > _state!.Balance,
            HorizontalExpand = true,
            StyleBoxOverride = CreateActionButtonStyle("#c79612", "#f0d36f"),
        };
        buy.Label.FontColorOverride = Color.White;
        buy.OnPressed += _ => OnBuy?.Invoke(item.CommodityId);
        actions.AddChild(buy);
        if (HasSection(item, TradingMarketSection.Unique))
        {
            var sell = new Button
            {
                Text = item.HighestBuyPrice?.ToString() ?? "—",
                Disabled = item.HighestBuyPrice == null,
                HorizontalExpand = true,
                Margin = new Thickness(4, 0, 0, 0),
                StyleBoxOverride = CreateActionButtonStyle("#b13a3a", "#e66b63"),
            };
            sell.Label.FontColorOverride = Color.White;
            sell.OnPressed += _ => OnSell?.Invoke(item.CommodityId);
            actions.AddChild(sell);
        }
        content.AddChild(actions);
        panel.AddChild(content);
        return panel;
    }

    private static StyleBoxFlat CreateActionButtonStyle(string background, string border)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex(background),
            BorderColor = Color.FromHex(border),
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 6,
            ContentMarginRightOverride = 6,
            ContentMarginTopOverride = 3,
            ContentMarginBottomOverride = 3,
        };
    }

    private void RebuildSelected()
    {
        OffersContainer.DisposeAllChildren();
        if (_management || _archive || _state == null || _selected == null)
        {
            SelectedName.Text = "Выберите товар";
            SelectedName.FontColorOverride = null;
            SelectedPreview.DisposeAllChildren();
            SelectedStats.SetMarkup(string.Empty);
            CreateBuyOrderButton.Disabled = true;
            return;
        }

        var item = _state.Items.FirstOrDefault(value => value.CommodityId == _selected.Value);
        if (item == null)
            return;

        SelectedName.Text = item.DisplayName;
        SelectedName.FontColorOverride = item.IsDamagedEquipment ? Color.FromHex("#e65353") : null;
        SelectedPreview.DisposeAllChildren();
        SelectedPreview.AddChild(CreateItemPreview(item, new Vector2(96, 96)));
        SelectedStats.SetMarkup(
            $"Лоты: {item.SellOfferCount} · Заказы: {item.BuyOfferCount}");
        CreateBuyOrderButton.Disabled = false;

        var offers = _state.Offers
            .Where(offer => offer.CommodityId == item.CommodityId)
            .OrderBy(offer => offer.Side)
            .ThenBy(offer => offer.Side == TradingOfferSide.Sell ? offer.Price : -offer.Price);
        foreach (var offer in offers)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 3),
            };
            row.AddChild(new Label
            {
                Text = offer.Side == TradingOfferSide.Sell ? "Лот" : "Заказ",
                MinWidth = 54,
            });
            row.AddChild(new Label
            {
                Text = offer.ParticipantName,
                HorizontalExpand = true,
                ClipText = true,
            });
            if (offer.Side == TradingOfferSide.Sell || HasSection(item, TradingMarketSection.Unique))
            {
                var action = new Button
                {
                    Text = offer.Price.ToString(),
                    MinWidth = 76,
                    Disabled = offer.IsOwn ||
                               offer.Side == TradingOfferSide.Sell && offer.Price > _state.Balance,
                    StyleBoxOverride = offer.Side == TradingOfferSide.Sell
                        ? CreateActionButtonStyle("#c79612", "#f0d36f")
                        : CreateActionButtonStyle("#b13a3a", "#e66b63"),
                };
                action.Label.FontColorOverride = Color.White;
                action.OnPressed += _ =>
                {
                    if (offer.Side == TradingOfferSide.Sell)
                        OnBuyOffer?.Invoke(offer.Id);
                    else
                        OnSellOffer?.Invoke(offer.Id);
                };
                row.AddChild(action);
            }
            else
            {
                row.AddChild(new Label
                {
                    Text = offer.Price.ToString(),
                    MinWidth = 76,
                    Align = Label.AlignMode.Center,
                });
            }
            if (offer.IsOwn)
            {
                var cancel = new Button { Text = "×", MinWidth = 28 };
                cancel.OnPressed += _ => OnCancelOffer?.Invoke(offer.Id);
                row.AddChild(cancel);
            }
            OffersContainer.AddChild(row);
        }
    }

    private void CreateSelectedBuyOrder()
    {
        if (_selected == null || !TryParsePrice(BuyPrice.Text, out var price))
            return;
        OnCreateBuyOffer?.Invoke(_selected.Value, price);
    }

    private void RebuildManagement()
    {
        ManagedOffersContainer.DisposeAllChildren();
        StoredItemsContainer.DisposeAllChildren();
        if (_state == null)
            return;

        var ownOffers = _state.Offers.Where(offer => offer.IsOwn).ToList();
        if (ownOffers.Count == 0)
            ManagedOffersContainer.AddChild(new Label { Text = "Нет активных лотов и заказов" });

        foreach (var offer in ownOffers)
        {
            var row = CreateManagementRow(
                offer.ProductEntity,
                offer.PreviewEntity,
                offer.DisplayName,
                offer.Side == TradingOfferSide.Sell
                    ? $"Лот · {offer.Price}"
                    : $"Заказ · {offer.Price}");
            var cancel = new Button
            {
                Text = offer.Side == TradingOfferSide.Sell ? "Отменить и забрать" : "Отменить",
                MinWidth = 150,
            };
            cancel.OnPressed += _ => OnCancelOffer?.Invoke(offer.Id);
            row.AddChild(cancel);
            ManagedOffersContainer.AddChild(row);
        }

        if (_state.StoredItems.Count == 0)
            StoredItemsContainer.AddChild(new Label { Text = "Нет предметов для получения" });

        foreach (var stored in _state.StoredItems)
        {
            var row = CreateManagementRow(
                stored.ProductEntity,
                stored.Item,
                stored.DisplayName,
                "Получен по заказу");
            var collect = new Button { Text = "Получить", MinWidth = 150 };
            collect.OnPressed += _ => OnCollectStoredItem?.Invoke(stored.Item);
            row.AddChild(collect);
            StoredItemsContainer.AddChild(row);
        }
    }

    private void RebuildArchive()
    {
        ArchiveContainer.DisposeAllChildren();
        if (_state == null)
            return;

        if (_state.Archive.Count == 0)
        {
            ArchiveContainer.AddChild(new Label
            {
                Text = "Архив сделок пуст",
                Margin = new Thickness(4),
            });
            return;
        }

        foreach (var message in _state.Archive.AsEnumerable().Reverse())
        {
            ArchiveContainer.AddChild(new Label
            {
                Text = message,
                ToolTip = message,
                HorizontalExpand = true,
                ClipText = true,
                Margin = new Thickness(4, 2),
            });
        }
    }

    private BoxContainer CreateManagementRow(
        EntProtoId product,
        NetEntity? preview,
        string displayName,
        string status)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(4),
        };
        row.AddChild(CreateItemPreview(product, preview, new Vector2(54, 54)));
        var labels = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(8, 0),
        };
        labels.AddChild(new Label { Text = displayName, ClipText = true });
        labels.AddChild(new Label { Text = status, StyleClasses = { "LabelSubText" } });
        row.AddChild(labels);
        return row;
    }

    private static void SubmitPrice(string text, Action<int>? action)
    {
        if (TryParsePrice(text, out var price))
            action?.Invoke(price);
    }

    private static bool TryParsePrice(string text, out int price)
    {
        return int.TryParse(text, out price) && price > 0;
    }

    private Control CreateItemPreview(TradingMarketItemState item, Vector2 size)
    {
        return CreateItemPreview(item.ProductEntity, item.PreviewEntity, size);
    }

    private Control CreateItemPreview(EntProtoId product, NetEntity? preview, Vector2 size)
    {
        if (preview is { } netEntity)
        {
            var view = new SpriteView
            {
                MinSize = size,
                SetSize = size,
                Stretch = SpriteView.StretchMode.Fill,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                MouseFilter = Control.MouseFilterMode.Pass,
            };
            view.SetEntity(netEntity);
            view.OnKeyBindDown += args =>
            {
                if (args.Function != ContentKeyFunctions.ExamineEntity ||
                    view.Entity is not { } viewed ||
                    !_entities.EntityExists(viewed.Owner))
                {
                    return;
                }

                _entities.System<ExamineSystem>().DoExamine(viewed.Owner, ignoreRange: true);
                args.Handle();
            };
            return view;
        }

        if (_prototypes.HasIndex(product))
        {
            var icon = new TextureRect
            {
                Texture = _entities.System<SpriteSystem>().GetPrototypeIcon(product).Default,
                MinSize = size,
                SetSize = size,
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                MouseFilter = Control.MouseFilterMode.Pass,
            };
            icon.OnKeyBindDown += args =>
            {
                if (args.Function != ContentKeyFunctions.ExamineEntity)
                    return;

                var viewed = GetPrototypeExamineEntity(product);
                _entities.System<ExamineSystem>().DoExamine(viewed, ignoreRange: true);
                args.Handle();
            };
            return icon;
        }

        return new Control
        {
            MinSize = size,
            SetSize = size,
        };
    }

    private EntityUid GetPrototypeExamineEntity(EntProtoId product)
    {
        if (_prototypeExamineEntities.TryGetValue(product, out var entity) &&
            _entities.EntityExists(entity))
        {
            return entity;
        }

        entity = _entities.SpawnEntity(product, MapCoordinates.Nullspace);
        _prototypeExamineEntities[product] = entity;
        return entity;
    }

    private static bool HasSection(TradingMarketItemState item, TradingMarketSection section)
    {
        return (item.Sections & section) != 0;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateHeldItem();
    }

    private void UpdateHeldItem()
    {
        var canOffer = false;
        if (_state == null ||
            _entities.System<HandsSystem>().GetActiveHandEntity() is not { } held ||
            !_entities.EntityExists(held) ||
            !_entities.TryGetComponent<MetaDataComponent>(held, out var metadata) ||
            metadata.EntityPrototype?.ID is not { } product ||
            !_entities.HasComponent<ItemComponent>(held))
        {
            UpdateHeldItemAvailability(canOffer);
            return;
        }

        if (_prototypes.TryIndex(product, out var prototype) &&
            prototype.TryGetComponent<MedievalCurrencyComponent>(out _, _entities.ComponentFactory))
        {
            UpdateHeldItemAvailability(canOffer);
            return;
        }

        canOffer = true;
        UpdateHeldItemAvailability(canOffer);
    }

    private void UpdateHeldItemAvailability(bool canOffer)
    {
        CreateSellOfferButton.Disabled = !canOffer;
        CreateHeldBuyOrderButton.Disabled = !canOffer;
    }

    private void OpenWithdrawWindow()
    {
        if (_state == null || _currency == null)
            return;

        if (_withdrawWindow is { IsOpen: true })
        {
            _withdrawWindow.MoveToFront();
            return;
        }

        _withdrawWindow = new StoreWithdrawWindow();
        _withdrawWindow.OpenCentered();
        _withdrawWindow.CreateCurrencyButtons(new Dictionary<ProtoId<CurrencyPrototype>, FixedPoint2>
        {
            { _currency, _state.Balance },
        });
        _withdrawWindow.OnWithdrawAttempt += (_, _, amount) => OnWithdraw?.Invoke(amount);
    }

    private void UpdateColumns()
    {
        ItemsGrid.Columns = Math.Max(1, (int) (ItemsGrid.Width / 185));
    }

    public override void Close()
    {
        base.Close();
        _withdrawWindow?.Close();

        foreach (var entity in _prototypeExamineEntities.Values)
        {
            if (_entities.EntityExists(entity))
                _entities.QueueDeleteEntity(entity);
        }

        _prototypeExamineEntities.Clear();
    }
}
